- name: install apache and php packages
  tags: apache,apache2,php,httpd
  package: 
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service
  tags: httpd,apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail address for admin
  tags: apache,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "CentOS"
  notify: restart_apache

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: enable firewall and add default apps (Ubuntu)
  tags: firewall
  ufw:
    state: enabled
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '5666'
    - '22'
    - '80'
  when: ansible_distribution == "Ubuntu"
  notify: reload_ufw

- name: enable firewall and add default apps (CentOS)
  tags: firewall
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  when: ansible_distribution == "CentOS"
  loop:
    - 5666/tcp
    - 22/tcp
    - 80/tcp
  notify: reload_firewalld
