- name: add ssh key for ansuser
  authorized_key:
    user: ansuser
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILxqKB4y6oc6K/YF/ToqTjQ9lXUnWGgGVjc69M/nC6lJ ansible"

- name: generate sshd_config file from template
  tags: ssh
  template: 
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

- name: install Centos dependencies
  tags: centos,nrpe
  dnf:
    name:
      - epel-release
    state: latest
  when: ansible_distribution == "CentosOS"
  
- name: install nagios nrpe
  tags: nrpe
  package:
    name:
      - "{{ nrpe_package_name }}" 
      - "{{ nrpe_monitoring_package_name }}"
    state: latest

- name: start and enable nrpe service
  tags: nrpe
  service: 
    name: "{{ nrpe_package_name }}"
    state: started
    enabled: yes

- name: generate nrpe file from template
  tags: nrpe
  template: 
    src: "{{ nrpe_template_file }}"
    dest: /etc/nagios/nrpe.cfg
    owner: root
    group: root
    mode: 0644
  notify: restart_nrpe

- name: enable firewall and add default apps (Ubuntu)
  tags: firewall
  ufw:
    state: enabled
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '5666'
    - '22'
  when: ansible_distribution == "Ubuntu"
  notify: reload_ufw

- name: enable firewall and add default apps (CentOS)
  tags: firewall
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  when: ansible_distribution == "CentOS"
  loop:
    - 5666/tcp
    - 22/tcp
  notify: reload_firewalld

- name: set timezone to Australia/Melbourne
  timezone: 
    name: Australia/Melbourne  