- name: add ssh key for ansuser
  authorized_key:
    user: ansuser
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILxqKB4y6oc6K/YF/ToqTjQ9lXUnWGgGVjc69M/nC6lJ ansible"

- name: generate sshd_config file from template
  tags: ssh
  template: 
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

- name: set timezone to Australia/Melbourne
  timezone: 
    name: Australia/Melbourne  